name: Exemple cicd
on:
    push:
        branches: [main]

jobs:
    build-and-bandit:
        runs-on: windows-latest
        steps: 
            - name: recup depot
              uses: actions/checkout@v7

            # - name: créer un venv
            #   run:  python -m venv venv

            # - name: activer le venv
            # # powershell
            #   run: venv\Scripts\Activate.ps1 

            - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
              uses: actions/setup-python@v5

            - name: installation requirements 
              run: pip install -r requirements.txt


            - name: installation package bandit 
              run: pip install bandit

            - name: demarrer bandit 
              run: bandit -r ex_react_2/src --severity-level:medium